import pika

connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
channel = connection.channel()
channel.queue_declare("hello")
channel.basic_publish(exchange='', routing_key='hello', body="hello, RabbitMQ!,,, first")
channel.basic_publish(exchange='', routing_key='hello', body="hello, RabbitMQ!")
channel.basic_publish(exchange='', routing_key='hello', body="hello, RabbitMQ!, second")
channel.basic_publish(exchange='', routing_key='dt', body="hello, RabbitMQ!, third")
print("[x] Sent 'hello, RabbitMQ!,,, first'")
print("[x] Sent 'hello, RabbitMQ!'")
print("[x] Sent 'hello, RabbitMQ!, second'")
print("[x] Sent 'hello, RabbitMQ!, third'")
channel.queue_delete('dt')
channel.queue_declare('dt')
channel.basic_publish(exchange='', routing_key='dt', body="hello, dt RabbitMQ!,,, first")
channel.basic_publish(exchange='', routing_key='dt', body="hello, dt RabbitMQ!")
channel.basic_publish(exchange='', routing_key='dt', body="hello, dt RabbitMQ!, second")
channel.basic_publish(exchange='', routing_key='dt', body="hello, dt RabbitMQ!, third")
print("[x] Sent 'hello, RabbitMQ!,,, first'")
print("[x] Sent 'hello, RabbitMQ!'")
print("[x] Sent 'hello, RabbitMQ!, second'")
print("[x] Sent 'hello, RabbitMQ!, third'")
connection.close()